name: Bake Lighting with VRAD

on:
  workflow_dispatch:

jobs:
  bake-lm:
    runs-on: windows-latest
    steps:
      - name: Setup Environment
        shell: cmd
        env:
          USERNAME: ${{ secrets.STEAM_USERNAME }}
          PASSWORD: ${{ secrets.STEAM_PASSWORD }}
        run: |
          %CD%\steamcmd\steamcmd.exe +login %USERNAME% %PASSWORD% +force_install_dir "..\Half-Life 2" +app_update 220 +exit
          copy "%CD%\depends\Vrad_fix\HUGE_lights.rad" ".\Half-Life 2\hl2\"
          FOR /F "tokens=*" %%G IN ('dir /b "%CD%\Half-Life 2\hl2\maps\*.bsp"') DO copy "%CD%\Half-Life 2\hl2\maps\%%G" "%CD%\map_enhance_mod\maps\"
          copy "%CD%\depends\slammin\vrad.exe" "%CD%\Half-Life 2\bin\"
          copy "%CD%\depends\slammin\vrad_dll.dll" "%CD%\Half-Life 2\bin\"

      - name: Bake Lightmaps
        shell: cmd
        run: |
          FOR /F "tokens=*" %%G IN ('dir /b %CD%\map_enhance_mod\maps\*.bsp') DO "%CD%\Half-Life 2\bin\vrad.exe" "%CD%\map_enhance_mod\maps\%%G" -lights "%CD%\Half-Life 2\hl2\HUGE_lights.rad" -both -TextureShadows -staticproplighting -StaticPropPolys -game "%CD%\Half-Life 2\hl2"

      - uses: actions/upload-artifact@v4
        with:
          name: Lighting Mod
          path: map_enhance_mod
