name: Bake Lighting with VRAD

on:
  workflow_dispatch:

jobs:
  bake-lm:
    runs-on: windows-latest
    environment: hl2
    steps:

      - name: Clone repo
        uses: GuillaumeFalourd/clone-github-repo-action@v2.3
        with:
          depth: 1
          branch: 'main'
          owner: 'EternallyEmber'
          repository: 'vrad-recompile'

      - name: Setup Environment
        shell: cmd
        env:
          STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
          STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
        run: |
          cd vrad-recompile
          %CD%\setupenv.cmd

      - name: Bake Lightmaps
        shell: cmd
        run: |
          cd vrad-recompile
          %CD%\lightmap.bat

      - uses: actions/upload-artifact@v4
        with:
          name: Lighting Mod
          path: map_enhance_mod
