name: Bake Lighting with VRAD

on:
  workflow_dispatch:

jobs:
  bake-lm:
    runs-on: windows-latest
    steps:
      - name: Setup Environment
        shell: cmd
        env:
          USERNAME: ${{ secrets.STEAM_USERNAME }}
          PASSWORD: ${{ secrets.STEAM_PASSWORD }}
        run: |
          cmd /C %CD%\setupenv.cmd

      - name: Bake Lightmaps
        shell: cmd
        run: |
          cmd /C %CD%\lightmap.cmd

      - uses: actions/upload-artifact@v4
        with:
          name: Lighting Mod
          path: map_enhance_mod
